version: '3'
services:
  deep-learn:
    image: scotang/docker-python-deep-learning:latest
    depends_on:
     - db
    ports:
     - "8888:8888"
    tty: true
    stdin_open: true
    restart: always
    environment:
      DB_HOST: db:3306
  db:
    image: mysql:latest
    ports:
      - "33066:3306"
    volumes:
     - ./data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: stock
      MYSQL_USER: user
      MYSQL_PASSWORD: userpwd